# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
    - -s -w -X main.version={{ .Env.GITSPORK_VERSION }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates: ["rockholla/gitspork:{{ .Tag }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates: ["--platform=linux/amd64"]
  - image_templates: ["rockholla/gitspork:{{ .Tag }}-arm64"]
    goarch: arm64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates: ["--platform=linux/arm64"]
  - image_templates: ["rockholla/gitspork:{{ .Tag }}-armv7"]
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates: ["--platform=linux/arm/v7"]
  - image_templates: ["rockholla/gitspork:{{ .Tag }}-armv6"]
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates: ["--platform=linux/arm/v6"]
  - image_templates: ["rockholla/gitspork:{{ .Tag }}-386"]
    goarch: "386"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates: ["--platform=linux/386"]

docker_manifests:
  - name_template: "rockholla/gitspork:{{ .Tag }}"
    image_templates:
      - "rockholla/gitspork:{{ .Tag }}-amd64"
      - "rockholla/gitspork:{{ .Tag }}-arm64"
      - "rockholla/gitspork:{{ .Tag }}-armv7"
      - "rockholla/gitspork:{{ .Tag }}-armv6"
      - "rockholla/gitspork:{{ .Tag }}-386"
  - name_template: "rockholla/gitspork:latest"
    skip_push: '{{ ne .Env.IS_LATEST "true" }}'
    image_templates:
      - "rockholla/gitspork:{{ .Tag }}-amd64"
      - "rockholla/gitspork:{{ .Tag }}-arm64"
      - "rockholla/gitspork:{{ .Tag }}-armv7"
      - "rockholla/gitspork:{{ .Tag }}-armv6"
      - "rockholla/gitspork:{{ .Tag }}-386"

release:
  prerelease: auto
  footer: >-
    Container image containing a usable gitspork binary available at https://hub.docker.com/r/rockholla/gitspork/tags?name={{ .Tag }}
