# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: linux
    main: ./cmd/gitspork
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ .Tag }}
  - id: darwin
    main: ./cmd/gitspork
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Tag }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc

dockers:
  - ids: [linux]
    image_templates: ["rockholla/gitspork:{{ .Tag }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates: ["--platform=linux/amd64", "--provenance=false"]
  - ids: [linux]
    image_templates: ["rockholla/gitspork:{{ .Tag }}-arm64"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates: ["--platform=linux/arm64", "--provenance=false"]
  - ids: [linux]
    image_templates: ["rockholla/gitspork:{{ .Tag }}-armv7"]
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates: ["--platform=linux/arm/v7", "--provenance=false"]
  - ids: [linux]
    image_templates: ["rockholla/gitspork:{{ .Tag }}-armv6"]
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates: ["--platform=linux/arm/v6", "--provenance=false"]
  - ids: [linux]
    image_templates: ["rockholla/gitspork:{{ .Tag }}-386"]
    goarch: "386"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates: ["--platform=linux/386", "--provenance=false"]

docker_manifests:
  - name_template: "rockholla/gitspork:{{ .Tag }}"
    image_templates:
      - "rockholla/gitspork:{{ .Tag }}-amd64"
      - "rockholla/gitspork:{{ .Tag }}-arm64"
      - "rockholla/gitspork:{{ .Tag }}-armv7"
      - "rockholla/gitspork:{{ .Tag }}-armv6"
      - "rockholla/gitspork:{{ .Tag }}-386"
  - name_template: "rockholla/gitspork:latest"
    skip_push: '{{ if .Prerelease }}true{{ else }}false{{ end }}'
    image_templates:
      - "rockholla/gitspork:{{ .Tag }}-amd64"
      - "rockholla/gitspork:{{ .Tag }}-arm64"
      - "rockholla/gitspork:{{ .Tag }}-armv7"
      - "rockholla/gitspork:{{ .Tag }}-armv6"
      - "rockholla/gitspork:{{ .Tag }}-386"

brews:
  - name: gitspork
    directory: Formula
    repository:
      owner: rockholla
      name: homebrew-gitspork
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/rockholla/gitspork"
    description: "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
    license: "MIT"
    install: |
      bin.install "gitspork"
    test: |
      system "#{bin}/gitspork", "--version"

release:
  prerelease: auto
  replace_existing_artifacts: true
  footer: >-
    Container image containing a usable gitspork binary available at https://hub.docker.com/r/rockholla/gitspork/tags?name={{ .Tag }}
