version: dev
upstream_owned:
- upstream-owned/*
- upstream-owned.mk
downstream_owned:
- downstream-owned.md
shared_ownership:
  merged:
  - Makefile
  - shared-ownership-merge.txt
  - sub/shared-ownership-merge.md
  structured:
    prefer_upstream:
    - config.yaml
    prefer_downstream:
    - info.json


