version: dev
upstream_owned:
- upstream-owned/**/*
- upstream-owned.mk
downstream_owned:
- downstream-owned.md
shared_ownership:
  merged:
  - Makefile
  - shared-ownership-merge.txt
  - sub/shared-ownership-merge.md
  structured:
    prefer_upstream:
    - config.yaml
    prefer_downstream:
    - info.json
templated:
- template: .gitspork-templates/meta.txt.go.tmpl
  destination: meta.txt
  inputs:
  - name: project_name
    json_data_path: ../templated-json-input-data.json
  - name: project_description
    json_data_path: ../templated-json-input-data.json
migrations:
- .gitspork/migration-001.yml


