templated:
- template: config.yml.go.tmpl
  destination: config.yml
  inputs:
  - name: one
    prompt: value for one
  - name: two
    prompt: value for two
- template: config-alt.yml.go.tmpl
  destination: config-alt.yml
  merged:
    structured: prefer-downstream
  inputs:
  - name: three
    json_data_path: ../data.json
  - name: four
    json_data_path: ../data.json
  - name: five
    previous_input:
      template: config.yml.go.tmpl
      name: two
